### ISSUE TITLE
address record deleted if no ip is returned

### ISSUE THREAD

**Issue by pcallycat** [mhum/nfs-dynamic-dns#13]
If the services returns no ip address information, I think the script and nfs's api are deleting the address record completely.  Unfortunately I haven't been able to duplicate because I don't always catch it in time to verify the data the service is returning.

**Comment by mhum** [comment]
Oof, that's not great! I'll have a look this weekend and see if I can fix that. Thanks for the report!

**Comment by mhum** [comment]
@pcallycat, I've released a new version that should hopefully resolve this issue you've been seeing.

When the script detected that the IP addresses didn't match, it would be two API calls to NFS:
1. First remove the domain/subdomain
2. Add the domain/subdomain with the new IP address

What I suspect was happening is that it was attempting to set an invalid IPV4 IP address and the second API call failed. Since the first step was to remove the domain/subdomain, you'd get into the state you described. If you've been saving the script's stdout anywhere, you should see in the logs what address it was trying to set. My guess is the call to the IP address provider was returning a non-IPV4 address and instead was an error or something else. 

Years ago when I had Comcast as my ISP, they were injecting code directly into the response body breaking this script in the way that you're seeing :sob: Maybe at some point I'll update the script to require an HTTPS IP provider to prevent that issue (it's using http://ipinfo.io/ip by default currently).

I've updated the script to instead use the [replaceRR](https://members.nearlyfreespeech.net/wiki/API/DNSReplaceRR) API instead. This does the removal and add atomically. So if the update fails, the domain/subdomain won't be removed. I've also updated the script to output an errors the API responds with. If my suspicions are correct, you should see some errors from the script's stdout every now and again.

**Comment by pcallycat** [comment]
I was using the default provider at the time. Looking at the logs, at the time it failed, no ip was returned (which leads me to believe you are correct in the cause) I did manage to verify this by visiting the url used in the script after I posted the issue, it basically returned a blank page. I’ve updated my script, and truly appreciate your fix on this. I’d hoped to look at it myself and continue, but you were much faster than I. Thanks again :) On Dec 17, 2023, at 13:11, Michael Humiston ***@***.***> wrote:﻿
@pcallycat, I've released a new version that should hopefully resolve this issue you've been seeing.
When the script detected that the IP addresses didn't match, it would be two API calls to NFS:

First remove the domain/subdomain
Add the domain/subdomain with the new IP address

What I suspect was happening is that it was attempting to set an invalid IPV4 IP address and the second API call failed. Since the first step was to remove the domain/subdomain, you'd get into the state you described. If you've been saving the script's stdout anywhere, you should see in the logs what address it was trying to set. My guess is the call to the IP address provider was returning a non-IPV4 address and instead was an error or something else.
Years ago when I had Comcast as my ISP, they were injecting code directly into the response body breaking this script in the way that you're seeing 😭 Maybe at some point I'll update the script to require an HTTPS IP provider to prevent that issue (it's using http://ipinfo.io/ip by default currently).
I've updated the script to instead use the replaceRR API instead. This does the removal and add atomically. So if the update fails, the domain/subdomain won't be removed. I've also updated the script to output an errors the API responds with. If my suspicions are correct, you should see some errors from the script's stdout every now and again.
