### ISSUE TITLE
Curious why this is written in TCL script

### ISSUE THREAD

**Issue by MoralCode** [mhum/nfs-dynamic-dns#15]
on the rare occasion i want to contribute to this, I primarily find myself running into issues based on my lack of understanding of TCL syntax.

I'd be curious to learn why TCL script was chosen as a language for this project

**Comment by mhum** [comment]
Hi @MoralCode,

Tcl was the server-side language I was using professionally at the time and the scripting language I was most familiar with back then. If I were to do this again, I'd definitely pick a different language. I always have to do a short relearning session whenever I make changes to this project since it's been a while that I've worked with Tcl 😅 Sometimes I think about re-writing this in JavaScript/Python/Ruby, but it's never at the top of my list since the project continues to work as-is for me.

**Comment by MoralCode** [comment]
Aight, i might take a shot at a python rewrite then cuz i kinds want to see if i can get ipv6 working

**Comment by mhum** [comment]
Neat! That would definitely be a useful feature. If you do the rewrite and want to continue adding features, I'd be happy to update the README of this project to point folks to your rewrite.

**Comment by MoralCode** [comment]
> Neat! That would definitely be a useful feature. If you do the rewrite and want to continue adding features, I'd be happy to update the README of this project to point folks to your rewrite.

oh i was just planning to contribute it back to your codebase haha - whatever works for you though

I will say the new code (once the python, dockerfile, and ipv6 branches are all merged in) should act basically the same as the old code, so it should be a drop-in replacement for anyone who is using this via docker

**Comment by mhum** [comment]
Apologies for taking a bit to review your PRs! It's been a busy week. Happy to continue accepting your changes into this project. I just don't want to be a blocker on reviewing PRs if you wanted to iterate on changes quickly.

**Comment by MoralCode** [comment]
closed by #16
