### ISSUE TITLE
IP lookup source is dead

### ISSUE THREAD

**Issue by keylogthis** [mhum/nfs-dynamic-dns#4]
This project is no longer working because the IP lookup source that you are using doesn't exist any longer.

Please update the IP lookup source in packages/http.tcl

Line 34

I set to http://ident.me/ and it works for me, but if anyone else tries to use this project as is, it will not work without it being fixed. Thank you.

**Comment by mhum** [comment]
Weird! This is a classic Works For Me™ scenario. I just ran the script on my server and checked the URL directly in my browser. The existing source worked in both places. 

Maybe I can expose a config that lets users override the default IP provider with their own?

**Comment by keylogthis** [comment]
You're right, it's my DNS ad blocker AdGuard Home blocking it, the default block list has the ipinfo.io domain in it.

https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

So I was wrong, the site is up and working. Disregard.

**Comment by mhum** [comment]
This is a bit overdue, but I added support to the script for providing an alternative IP lookup source.

The script has changed a bit since you originally created this issue and PR. The configs are no longer hard-coded into the script and instead are environmental variables. One of those environmental variables is for an alternative IP lookup source.
